#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#

name: build-mediatek_filogic

permissions: write-all
#ÂºÄÂêØÂÜôÊùÉÈôêÔºåÈò≤Ê≠¢Êó†Ê≥ï‰∏ä‰º†Âà∞release

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
   - cron: 0 20 * * 3
   #     ÂàÜ,Êó∂,Êó•,Êúà,Âë®„ÄÇÊØèÂë®Âõõ 20Êó∂ÊâßË°å‰∏ÄÊ¨° (UTCÊó∂Èó¥)
  
env:
  FREE_DISK_SH: scripts/free_disk_space.sh
  ENV_SH: scripts/environment.sh
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  PLATFORM_FILE: configs/filogic.txt
  CONFIG_FILE: configs/packages-L.txt
  #CONFIG_5G: configs/packages-5G.txt
  SETTINGS_SH: scripts/init-settings.sh
  PACKAGES_SH: scripts/packages.sh
  INSTALL5G_SH: scripts/install-5G.sh
  CLASH_CORE_SH: scripts/preset-clash-core-arm64-L.sh
  ADDMOUNT_SH: scripts/add_automount.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: false
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Ê£ÄÊü•
      uses: actions/checkout@main

    - name: ÂàùÂßãÂåñÁéØÂ¢É
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        chmod +x $FREE_DISK_SH && $FREE_DISK_SH
        sudo -E apt-get -qq update -y
        sudo -E apt-get -qq full-upgrade -y
        chmod +x $ENV_SH && $ENV_SH
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo timedatectl set-timezone "$TZ"
        docker image prune -a -f
        docker container prune -f
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: Ê£ÄÊü•Á©∫Èó¥‰ΩøÁî®ÊÉÖÂÜµ1
      if: (!cancelled())
      run: df -hT

    - name: ÂÖãÈöÜÊ∫êÁ†Å
      working-directory: /workdir
      run: |
        git clone $REPO_URL --depth 1 -b $REPO_BRANCH openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

    - name: ÂºÄÂêØÁºìÂ≠ò
      uses: klever1988/cachewrtbuild@main
      with:
        ccache: 'true'
        mixkey: 'filogic'
        prefix: ${{ github.workspace }}/openwrt

    - name: ÂÆâË£Ö feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: ÂØºÂÖ•Ë°•‰∏ÅÂíåÈÖçÁΩÆ & ÊâßË°åËÑöÊú¨
      run: |
        [ -d files ] && mv files openwrt/files || echo "files not found"
        #[ -f $CONFIG_5G ] && cat $CONFIG_5G >> openwrt/.config
        [ -f $PLATFORM_FILE ] && cat $PLATFORM_FILE >> openwrt/.config
        [ -f $CONFIG_FILE ] && cat $CONFIG_FILE >> openwrt/.config
        cd openwrt
        chmod +x $GITHUB_WORKSPACE/$INSTALL5G_SH && $GITHUB_WORKSPACE/$INSTALL5G_SH
        chmod +x $GITHUB_WORKSPACE/$SETTINGS_SH && $GITHUB_WORKSPACE/$SETTINGS_SH
        chmod +x $GITHUB_WORKSPACE/$PACKAGES_SH && $GITHUB_WORKSPACE/$PACKAGES_SH
        chmod +x $GITHUB_WORKSPACE/$CLASH_CORE_SH && $GITHUB_WORKSPACE/$CLASH_CORE_SH
        chmod +x $GITHUB_WORKSPACE/$ADDMOUNT_SH && $GITHUB_WORKSPACE/$ADDMOUNT_SH

    # - name: ‰∏ãËΩΩÊñá‰ª∂
    #   run: |
    #     cd openwrt
    #     make defconfig
    #     make download -j8 V=10
    #     find dl -size -1024c -exec ls -l {} \;
    #     find dl -size -1024c -exec rm -f {} \;

    - name: Á©∫Èó¥‰ΩøÁî®ÊÉÖÂÜµ2
      if: (!cancelled())
      run: df -hT

    - name: ÁºñËØëÂ∑•ÂÖ∑Èìæ
      id: mtools
      run: |
        cd openwrt
        make defconfig
        echo -e "$(($(nproc)+1)) thread compile"
        make tools/compile -j$(($(nproc)+1)) || make tools/compile -j1 V=s
        make toolchain/compile -j$(($(nproc)+1)) || make toolchain/compile -j1 V=s
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Á©∫Èó¥‰ΩøÁî®ÊÉÖÂÜµ3_1
      if: (!cancelled())
      run: df -hT

    - name: Ê∏ÖÈô§Â∑•ÂÖ∑ÈìæÁºñËØë‰∏≠Èó¥‰∫ßÁâ©...
      if: steps.mtools.outputs.status == 'success' && !cancelled()
      run: |
        cd openwrt
        rm -rf dl/*
        rm -rf build_dir/toolchain-*

    - name: Á©∫Èó¥‰ΩøÁî®ÊÉÖÂÜµ3_2
      if: (!cancelled())
      run: df -hT

    - name: ÁºñËØëÂÜÖÊ†∏
      id: mkernel
      if: steps.mtools.outputs.status == 'success' && !cancelled()
      run: |
        cd openwrt
        echo -e "$(($(nproc)+1)) thread compile"
        make target/linux/compile -j$(($(nproc)+1)) || make target/linux/compile -j1 V=s
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Á©∫Èó¥‰ΩøÁî®ÊÉÖÂÜµ4
      if: (!cancelled())
      run: df -hT

    - name: ÁºñËØëÊèí‰ª∂
      id: mpackage
      if: steps.mkernel.outputs.status == 'success' && !cancelled()
      run: |
        cd openwrt
        echo -e "$(($(nproc)+1)) thread compile"
        make package/compile -j$(($(nproc)+1)) || make package/compile -j1 V=s
        make package/index
        make package/install -j$(nproc) || make package/install -j1 V=s
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Á©∫Èó¥‰ΩøÁî®ÊÉÖÂÜµ5
      if: (!cancelled())
      run: df -hT

    - name: Ê∏ÖÈô§Êèí‰ª∂ÁºñËØëÊñá‰ª∂
      id: cpackage
      if: steps.mpackage.outputs.status == 'success' && !cancelled()
      run: |
        cd openwrt
        rm -rf build_dir/target-*/host
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Á©∫Èó¥‰ΩøÁî®ÊÉÖÂÜµ6
      if: (!cancelled())
      run: df -hT

    - name: ÁºñËØëÂõ∫‰ª∂
      id: compile
      if: steps.cpackage.outputs.status == 'success' && !cancelled()
      run: |
        cd openwrt
        echo -e "$(($(nproc)+1)) thread compile"
        make target/install -j$(nproc) || make target/install -j1 V=s
        make json_overview_image_info
        make checksum
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Á©∫Èó¥‰ΩøÁî®ÊÉÖÂÜµ7
      if: (!cancelled())
      run: df -hT

    - name: ‰∏ä‰º† bin ÁõÆÂΩï
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      with:
        name: OpenWrt_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: openwrt/bin

    - name: Êï¥ÁêÜÊñá‰ª∂
      id: organize
      if: steps.compile.outputs.status == 'success'
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf *.buildinfo 
        rm -rf *.json 
        rm -rf *.manifest 
        rm -rf packages
        rm -rf *-kernel.bin
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Âõ∫‰ª∂ÈáçÂëΩÂêç
      if: steps.organize.outputs.status == 'success'
      shell: bash
      run: |
        cd openwrt/bin/targets/*/*
        for file in *mediatek-filogic-*.bin; do
          new_name=$(echo "$file" | sed 's/mediatek-filogic-//')
          mv -v "$file" "$new_name"
        done

    - name: ‰∏ä‰º†Âõ∫‰ª∂ÁõÆÂΩï
      uses: actions/upload-artifact@main
      if: env.UPLOAD_FIRMWARE == 'true' && steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}

    - name: ÁîüÊàêÂèëÂ∏ÉÊ†áÁ≠æ
      id: tag
      if: env.UPLOAD_RELEASE == 'true' && steps.compile.outputs.status == 'success' && !cancelled()
      run: |
        echo -e "üéâ mediatek filogicÂπ≥Âè∞\n‚úÖ ‰∏ªÁ∫øÊ∫êÁ†Å\n‚ùóÔ∏è ipÂú∞ÂùÄ : 192.168.8.1" >> release.txt
        echo "release_tag=$(date +"%Y.%m.%d_MTK")" >> $GITHUB_OUTPUT
        echo "status=success" >> $GITHUB_OUTPUT

    - name: ‰∏ä‰º†Âõ∫‰ª∂Âà∞ÂèëÂ∏É
      uses: softprops/action-gh-release@v2.0.4
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: ${{ env.FIRMWARE }}/*
